### ISSUE TITLE
get_crosstabs should run for 1 model, 1 parameter each time

### ISSUE THREAD

**Issue by saleiro** [dssg/aequitas-public#10]

**Comment by saleiro** [comment]
it runs for 1 model at a time. it runs for 1 or many parameters depending if threshold is None or loaded from the configs.yaml

**Comment by lorenh516** [comment]
Get crosstabs does not catch multiple model_ids, grouping all records by the model_id passed or default model_id (1). 

To decide: should get crosstabs support multi-model crosstabs, or should this be in a different function called multimodel_crosstabs? Could pass none and then runs for loop on all unique, or could pass list and runs on for loop on subset.
